### ISSUE TITLE
API endpoint changed

### ISSUE THREAD

**Issue by anonewb** [alankilalank/react-covid-19#3]
https://github.com/alankilalank/react-covid-19/blob/9546f536879ff7508534e0ebf28f2953a2bcdde7/src/components/CountryPicker.tsx#L48

Previously, all the countries were sent inside the object which actually was the wrong way of sending data, but now API endpoint is sending in the array. So make necessary changes as the country picker isn't working.

**Comment by alankilalank** [comment]
solved, thanks for pointing this out @anonewb 

[39d1197](https://github.com/alankilalank/react-covid-19/commit/39d11970cd83d1ea0342e43a5f1034a86e247772)
